version: '3.8'

services:
  fish-detection-app:
    image: ultralytics/ultralytics:latest
    container_name: fish-detection-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - .:/usr/src/app
    # Change this line to use the full path to your app.py
    command: /bin/bash -c "pip install flask && python /usr/src/app/app.py"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]